nameisis_translation_controllers:
    resource: ../../Controller/
    type: annotation
    prefix: /selonia

nameisis_default:
    path: /selonia
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: nameisis_translation_overview
        permanent: true
        keepRequestMethod: true
